#version: '3.5'

#services:

#  backend:
#    build:
#      dockerfile: Dockerfile
#    image: cms.webapi:latest
#    container_name: cms.webapi
#    restart: unless-stopped
#    ports:
#      - "7800:80"
#    environment:
#      - TZ=Asia/Ho_Chi_Minh
#      - ASPNETCORE_URLS=http://+:80
